### ISSUE TITLE
IPackageManager

### ISSUE THREAD

**Issue by thorn5918** [iamverycute/TAM#1]
老哥你好，import android.content.pm.IPackageManager;
import android.net.IConnectivityManager;报错，有空的话，您能否指点一下

**Comment by lalakii** [comment]
> 老哥你好，import android.content.pm.IPackageManager; import android.net.IConnectivityManager;报错，有空的话，您能否指点一下

[Android Hidden API](https://github.com/anggrayudi/android-hidden-api)

**Comment by thorn5918** [comment]
> > 老哥你好，import android.content.pm.IPackageManager; import android.netConnectivityManager;报，有空的话，你能不能指点一下。
> 
> [Android 隐藏 API](https://github.com/anggrayudi/android-hidden-api)

万分感谢

**Comment by lalakii** [comment]
finish
